bitget:
  base_url: 'https://api.bitget.com'
  websocket_public_url: 'wss://ws.bitget.com/v2/ws/public'
  websocket_private_url: 'wss://ws.bitget.com/v2/ws/private'

strategy:
  squirrel:
    product_type: 'USDT-FUTURES'
    intervals:
      - '5m'
    universe:
      - 'BTCUSDT'