name: 0458 Strategy

# 매일 UTC 0시 (KST 9시)
on:
  schedule:
    - cron: '0 0 * * *'  # Every day at UTC 0:00 (KST 9:00)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run_orders_and_notify:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    env:
      DB_URL: ${{ secrets.DB_URL }}
      BITGET_API_KEY: ${{ secrets.BITGET_API_KEY }}
      BITGET_API_SECRET: ${{ secrets.BITGET_API_SECRET }}
      BITGET_PASSPHRASE: ${{ secrets.BITGET_PASSPHRASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies via Poetry
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run 0458 Strategy
        id: collect
        env:
          TZ: Asia/Seoul
        run: |
          # Execute script with optional base_date
          poetry run python src/scripts/0458.py $BD

      - name: Send Slack notification
        if: always()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "0458 Strategy Execution Result",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "fields": [
                    {
                      "title": "Workflow",
                      "value": "${{ github.workflow }}",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    }
                  ]
                }
              ]
            }