name: Collect Daily Candles(KRX)

on:
  schedule:
    - cron: '0 13 * * 1-5' # 11:00(KST) PM weekday
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: ""
      end_date:
        description: "End date (YYYY-MM-DD)"
        required: true
        default: ""

concurrency:
  group: collect-daily-candles-krx-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run_orders_and_notify:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Trigger Script on EC2
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.GCP_CE_HOST }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          script: |
            ./collect_daily_candles_krx.py
            

      - name: Send Slack notification
        if: failure()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": ":x: Collect Daily Candles(KRX) Failed",
              "attachments": [
                {
                  "color": "danger",
                  "fields": [
                    {
                      "title": "Workflow",
                      "value": "${{ github.workflow }}",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    }
                  ]
                }
              ]
            }